Router.configure({
  layoutTemplate: 'layout'
});
Router.route('/',{name: 'homeEng'})
Router.route('/masterTaoMasaEng', {name: 'masterTaoMasaEng'})
Router.route('/pictureEng',{name: 'pictureEng'})
Router.route('/videoEng',{name: 'videoEng'})
Router.route('/testimonialEng',{name: 'testimonialEng'})
Router.route('/contactsEng',{name: 'contactsEng'})

Router.route('/basicEng',{name: 'basicEng'})
Router.route('/generalQiGongEng',{name: 'generalQiGongEng'})
Router.route('/innerSmileEng',{name: 'innerSmileEng'})
Router.route('/6HealingSoundsEng',{name: '6HealingSoundsEng'})
Router.route('/microcosmicOrbitEng',{name: 'microcosmicOrbitEng'})
Router.route('/taoYinEng',{name: 'taoYinEng'})

Router.route('/mediumEng',{name: 'mediumEng'})
Router.route('/emptyForceEng',{name: 'emptyForceEng'})
Router.route('/3Fire6DirectionsEng',{name: '3Fire6DirectionsEng'})
Router.route('/stemCellsSystemEng',{name: 'stemCellsSystemEng'})
Router.route('/sexualHealingQiGongManEng',{name: 'sexualHealingQiGongManEng'})
Router.route('/sexualHealingQiGongWomanEng',{name: 'sexualHealingQiGongWomanEng'})
Router.route('/sexualHealingQiGongCoupleEng',{name: 'sexualHealingQiGongCoupleEng'})

Router.route('/advanceEng',{name: 'advanceEng'})
Router.route('/fusionofthe5Element1Eng',{name: 'fusionofthe5Element1Eng'})
Router.route('/fusionofthe5Element2Eng',{name: 'fusionofthe5Element2Eng'})
Router.route('/fusionofthe5Element3Eng',{name: 'fusionofthe5Element3Eng'})
Router.route('/kujiInEng',{name: 'kujiInEng'})

Router.route('/hardQiGong5EnghardQiGong5Eng',{name: 'hardQiGong5Eng'})
Router.route('/hardQiGongFormEng',{name: 'hardQiGongFormEng'})
Router.route('/ironShirtQiGong1Eng',{name: 'ironShirtQiGong1Eng'})
Router.route('/ironShirtQiGong2Eng',{name: 'ironShirtQiGong2Eng'})
Router.route('/ironShirtQiGong3Eng',{name: 'ironShirtQiGong3Eng'})
Router.route('/tanTienQiGongEng',{name: 'tanTienQiGongEng'})
Router.route('/taiChiQiGong1Eng',{name: 'taiChiQiGong1Eng'})
Router.route('/taiChiQiGong2Eng',{name: 'taiChiQiGong2Eng'})
Router.route('/taiChiQiGong3Eng',{name: 'taiChiQiGong3Eng'})
Router.route('/taiChiQiBallEng',{name: 'taiChiQiBallEng'})
Router.route('/earthEng',{name: 'earthEng'})
Router.route('/waterEng',{name: 'waterEng'})
Router.route('/fireEng',{name: 'fireEng'})
Router.route('/WindEng',{name: 'WindEng'})
Router.route('/VoidEng',{name: 'VoidEng'})
Router.route('/internalOrganMassageEng',{name: 'internalOrganMassageEng'})
Router.route('/guashaEng',{name: 'guashaEng'})
Router.route('/cosmicHealingEng',{name: 'cosmicHealingEng'})
Router.route('/cuppingEng',{name: 'cuppingEng'})

//Italia
Router.route('/homeIta',{name: 'homeIta'})
Router.route('/chiSiamoIta',{name: 'chiSiamoIta'})
Router.route('/fotoIta',{name: 'fotoIta'})
Router.route('/videoIta',{name: 'videoIta'})
Router.route('/faqIta',{name: 'faqIta'})
Router.route('/testimonianzeIta',{name: 'testimonianzeIta'})
Router.route('/contattiIta',{name: 'contattiIta'})
Router.route('/workShopIta',{name: 'workShopIta'})

Router.route('/baseIta',{name: 'baseIta'})
Router.route('/generalQiGongIta',{name: 'generalQiGongIta'})
Router.route('/sorrisoInterioreIta',{name: 'sorrisoInterioreIta'})
Router.route('/seiSuoniCurativiIta',{name: 'seiSuoniCurativiIta'})
Router.route('/orbitaMicrocosmicaIta',{name: 'orbitaMicrocosmicaIta'})
Router.route('/taoYinIta',{name: 'taoYinIta'})

Router.route('/intermedioIta',{name: 'intermedioIta'})
Router.route('/forzaVuotaIta',{name: 'forzaVuotaItaIta'})
Router.route('/3Fuochi6DirezioniIta',{name: '3Fuochi6DirezioniIta'})
Router.route('/sistemaIta',{name: 'sistemaIta'})
Router.route('/qiGongSessualeMaschileIta',{name: 'qiGongSessualeMaschileIta'})
Router.route('/qiGongSessualeFemminileIta',{name: 'qiGongSessualeFemminileIta'})
Router.route('/qiGongSessualediCoppiaIta',{name: 'qiGongSessualediCoppiaIta'})

Router.route('/avanzatoIta',{name: 'avanzatoIta'})
Router.route('/fusionedei5Elementi1Ita',{name: 'fusionedei5Elementi1Ita'})
Router.route('/fusionedei5Elementi2Ita',{name: 'fusionedei5Elementi2Ita'})
Router.route('/fusionedei5Elementi3Ita',{name: 'fusionedei5Elementi3Ita'})
Router.route('/kujiInIta',{name: 'kujiInIta'})

Router.route('/5PratichediHardQiGongIta',{name: '5PratichediHardQiGongIta'})
Router.route('/formaHardQiGongIta',{name: 'formaHardQiGongIta'})
Router.route('/camiciadiFerro1Ita',{name: 'camiciadiFerro1Ita'})
Router.route('/camiciadiFerro2Ita',{name: 'camiciadiFerro2Ita'})
Router.route('/camiciadiFerro3Ita',{name: 'camiciadiFerro3Ita'})
Router.route('/tanTienQiGongIta',{name: 'tanTienQiGongIta'})
Router.route('/taiChiQiGong1Ita',{name: 'taiChiQiGong1Ita'})
Router.route('/taiChiQiGong2Ita',{name: 'taiChiQiGong2Ita'})
Router.route('/taiChiQiGong3Ita',{name: 'taiChiQiGong3Ita'})
Router.route('/taiChidellaSferaIta',{name: 'taiChidellaSferaIta'})

//Romania
Router.route('/homeRom',{name: 'homeRom'})
Router.route('/chisiamoRom',{name: 'chisiamoRom'})
Router.route('/fotoRom',{name: 'fotoRom'})
Router.route('/videoRom',{name: 'videoRom'})
Router.route('/faqRom',{name: 'faqRom'})
Router.route('/testimonianzeRom',{name: 'testimonianzeRom'})
Router.route('/contattiRom',{name: 'contattiRom'})
Router.route('/workShopRom',{name: 'workShopRom'})

Router.route('/baseRom',{name: 'baseRom'})
Router.route('/generalQiGongRom',{name: 'generalQiGongRom'})
Router.route('/sorrisoInterioreRom',{name: 'sorrisoInterioreRom'})
Router.route('/seiSuoniCurativiRom',{name: 'seiSuoniCurativiRom'})
Router.route('/orbitaMicrocosmicaRom',{name: 'orbitaMicrocosmicaRom'})
Router.route('/taoYinRom',{name: 'taoYinRom'})

Router.route('/intermedioRom',{name: 'intermedioRom'})
Router.route('/forzaVuotaRom',{name: 'forzaVuotaRom'})
Router.route('/3Fuochi6DirezioniRom',{name: '3Fuochi6DirezioniRom'})
Router.route('/sistemaRom',{name: 'sistemaRom'})
Router.route('/qiGongSessualeMaschileRom',{name: 'qiGongSessualeMaschileRom'})
Router.route('/qiGongSessualeFemminileRom',{name: 'qiGongSessualeFemminileRom'})
Router.route('/qiGongSessualediCoppiaRom',{name: 'qiGongSessualediCoppiaRom'})

Router.route('/avanzatoRom',{name: 'avanzatoRom'})
Router.route('/fusionedei5Elementi1Rom',{name: 'fusionedei5Elementi1Rom'})
Router.route('/fusionedei5Elementi2Rom',{name: 'fusionedei5Elementi2Rom'})
Router.route('/fusionedei5Elementi3Rom',{name: 'fusionedei5Elementi3Rom'})
Router.route('/kujiInRom',{name: 'kujiInRom'})


Router.route('/5PratichediHardQiGongRom',{name: '5PratichediHardQiGongRom'})
Router.route('/formaHardQiGongRom',{name: 'formaHardQiGongRom'})
Router.route('/camiciadiFerro1Rom',{name: 'camiciadiFerro1Rom'})
Router.route('/camiciadiFerro2Rom',{name: 'camiciadiFerro2Rom'})
Router.route('/camiciadiFerro3Rom',{name: 'camiciadiFerro3Rom'})
Router.route('/tanTienQiGongRom',{name: 'tanTienQiGongRom'})

Router.route('/taiChiQiGong1Rom',{name: 'taiChiQiGong1Rom'})
Router.route('/taiChiQiGong2Rom',{name: 'taiChiQiGong2Rom'})
Router.route('/taiChiQiGong3Rom',{name: 'taiChiQiGong3Rom'})
Router.route('/taiChidellaSferaRom',{name: 'taiChidellaSferaRom'})
//Router.route('/',{name: ''})
//Router.route('/',{name: ''})
